# Generated by Django 3.2.19 on 2023-05-24 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_filter', models.CharField(
                    choices=[(APARTMENT, 'Apartment'), (VILLA, 'Villa'),
                             (FARMHOUSE, 'Farmhouse'), (CONDOS, 'Condos'),
                             (TOWNHOUSE, 'Townhouse'), (DULEX, 'Duplex'),
                             (Studio, 'Studio'), (CHALET, 'Chalet')],
                    default='Appartment', max_length=32)),
                ('price', models.DecimalField(max_digits=10, decimal_places=2,
                                              default=0)),
                ('image', models.ImageField(blank=True,
                 default='../default_post_rgq6aq', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), (
                    'normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
